version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
environment:
  IBEXPERT_EMAIL:
    secure: BmfewXWhVrOwF+V9qErqnu63YtnnifLxZkxqa24oSsA=
  IBEXPERT_PASSWORD:
    secure: pe+xVz+nPncjckFDNKlgLw==
build:
  verbosity: minimal
build_script:
- cmd: build.cmd
test_script:
- cmd: test.cmd
artifacts:
- path: IBExpertUpdate\bin\Release\setup_personal.exe